### ISSUE TITLE
Bicubic PSNR values on Set5 that I get after the code are worse than shown in Image

### ISSUE THREAD

**Issue by sumedhpendurkar** [MarkPrecursor/SRCNN-keras#1]
The values I get are almost 2dB less for Bicubic interpolation.
Is the results page for your code ; or some other matlab implementation?

**Comment by MaokeAI** [comment]
the measurement of PSNR can refer the matlab code of http://mmlab.ie.cuhk.edu.hk/projects/SRCNN.html
