### ISSUE TITLE
Hi，MarkPrecursor

### ISSUE THREAD

**Issue by agingdata** [MarkPrecursor/SRCNN-keras#2]

**Comment by DLjiaerlin** [comment]
when I execute the main.py, the error is that OSError: Unable to open file (Unable to open file: name = './train.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)

**Comment by MaokeAI** [comment]
You need to first use the "prepare_data.py" to generate the "train.h5"，and then use the "main.py" for test. I think your error is because of wrong file path, please check if there have the file "train.h5"

**Comment by DLjiaerlin** [comment]
oh！I have solved this question, but I do not kown that "pre_adam30.jpg", where its use. PSNR.py ?

**Comment by fayazdharejo** [comment]
> oh！I have solved this question, but I do not kown that "pre_adam30.jpg", where its use. PSNR.py ?

Can you tell me how did you solve this issue to generate "train.h5" I am facing this issue also
