### ISSUE TITLE
Can this code really achieve the image's super resolution?

### ISSUE THREAD

**Issue by agingdata** [MarkPrecursor/SRCNN-keras#4]

**Comment by DLjiaerlin** [comment]
Can you give a reason? Or because I did not really understand your code, thanks a lot

**Comment by MaokeAI** [comment]
Super resolution can be seen as a kind of advanced image upscale algorithm, comparing with algorithms like Bicubic or bilinear. The use of this network is to add some detailed information to the up-sampled image, to make it looks more clear.
